app/styles/app.css
app/styles/components/notification.css
app/styles/components/score-table.css
app/styles/shadows.css
app/templates/components/notification.hbs
app/templates/components/score-table.hbs
package.json
yarn.lock

see https://github.com/salsify/ember-css-modules

Use `ember-css-modules` to organize CSS styles

---

app/controllers/application.js
app/controllers/index.js
app/services/scoring.js
app/templates/application.hbs
app/templates/index.hbs

We will want to display the map on all routes, not just `index`

Move `Map` component to the application template

---

app/services/map.js

Unfortunately, this changed recently... 😢

services/map: Adjust SkyLines map URL

---

app/templates/components/map.hbs

The task should be shown below the aircraft icons

Adjust layer order

---

app/components/aircraft-layer.js
app/components/aircraft-shadow-layer.js
app/components/fullscreen-button.js
app/components/map.js
app/components/score-table.js
app/components/task-layer.js
app/components/zoom-buttons.js
app/controllers/application.js
app/controllers/index.js
app/routes/application.js
app/routes/index.js
app/services/aircraft.js
app/services/ddb.js
app/services/filter.js
app/services/history.js
app/services/map.js
app/services/scoring.js
app/services/ws.js
package.json
yarn.lock

see https://www.pzuraq.com/ember-octane-update-landing-decorators/ 🎉

Convert to native ES6 classes

---

app/routes/index.js

not the best animation, but better than nothing :)

routes/index: Animate "zoom to" operation after task was loaded

---

config/environment.js
package.json
yarn.lock

Let's disable them while we still can... 😅

Disable prototype extensions

---

app/services/map.js

These are not necessary when running tests and slows them down unnecessarily...

map: Disable background layers while testing

---

app/styles/app.css
app/styles/components/notification.css
app/templates/components/notification.hbs
app/templates/index-loading.hbs

This makes the component more reusable in other contexts

Cleanup `Notification` component styling

---

.travis.yml
config/environment.js
package.json
tests/application/freestyle-test.js
tests/test-helpers/ddb.js
tests/test-helpers/percy.js
yarn.lock

This PR adds basic visual regression testing via http://percy.io/
see https://github.com/skylines-project/skylines/pull/890

Visual regression testing

---

.eslintrc.js
app/app.js
app/components/aircraft-layer.js
app/components/aircraft-shadow-layer.js
app/components/map.js
app/components/score-table.js
app/components/task-layer.js
app/controllers/application.js
app/router.js
app/routes/index.js
app/services/aircraft.js
app/services/ddb.js
app/services/filter.js
app/services/history.js
app/services/map.js
app/services/ws.js
lib/igc-replay/addon/services/igc-replay.js
package.json
tests/application/basic-test.js
tests/application/filter-loading-test.js
tests/application/freestyle-test.js
tests/services/ddb-test.js
tests/services/filter-test.js
tests/services/history-test.js
tests/services/ws-test.js
tests/test-helper.js
tests/test-helpers/percy.js
tests/utils/hash-to-qp-test.js
tests/utils/normalize-device-id-test.js
yarn.lock

ESLint: Use `eslint-plugin-import-helpers` to sort and group imports consistently

---

.eslintrc.js
app/router.js
app/services/aircraft.js
app/services/map.js

... to keep me from doing stupid things

ESLint: Enable more rules

---

.eslintrc.js
package.json
yarn.lock

see https://github.com/xjamundx/eslint-plugin-promise

ESLint: Add `eslint-plugin-promise` rules

---

app/components/aircraft-layer.js
app/components/aircraft-shadow-layer.js

This deemphasizes the irrelevant aircraft when a filter is used.

Reduce opacity for aircraft that are filtered out

---

app/utils/normalize-device-id.js
tests/utils/normalize-device-id-test.js

Resolves https://github.com/Turbo87/ogn-web-viewer/issues/112

normalize-device-id: Return `null` if something falsy is passed in

---

app/app.js
app/sentry.js
config/environment.js
package.json
yarn.lock

see https://github.com/simplabs/simplabs.github.io/pull/427

Replace `ember-cli-sentry` with `@sentry/browser`

---

app/components/score-table.js

because we want to know when things fail 😉

score-table: Send aeroscore exceptions to Sentry

---

app/formats.js
app/routes/application.js
app/services/intl.js
app/templates/components/score-table.hbs
app/templates/index-loading.hbs
config/ember-intl.js
config/environment.js
lib/igc-replay/addon/services/mock-server.js
package.json
tests/test-helpers/ddb.js
translations/de.yaml
translations/en.yaml
yarn.lock

Use `ember-intl` and `fluent-langneg` to translate the app

---

app/router.js
app/routes/404.js
app/styles/404.css
app/templates/404.hbs
app/templates/application.hbs
lib/freestyle/app/routes/freestyle.js
tests/application/404-test.js
translations/de.yaml
translations/en.yaml

Resolves https://github.com/Turbo87/ogn-web-viewer/issues/140

Add 404 page

---

app/components/task-layer.js
app/controllers/error.js
app/routes/error.js
app/routes/index.js
app/styles/error.css
app/templates/error.hbs
tests/application/filter-loading-test.js
tests/application/task-test.js
translations/de.yaml
translations/en.yaml

Resolves https://github.com/Turbo87/ogn-web-viewer/issues/139

Show dialog when errors are thrown

---

app/templates/application.hbs
app/templates/head.hbs
app/templates/strepla/competition.hbs
app/templates/strepla/competition/class.hbs
package.json
yarn.lock

Use `ember-page-title` to show StrePla competition name and class in the tab title

---

app/services/map.js

This enable keyboardZoom via +/- keys.

services/map: Fix keyboard controls

---

lib/ember-data-strepla/app/models/strepla-task.js

strepla-task: Add support for `Racing-Task (RT) Regatta Start` rule name
